service: video-compressor

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

plugins:
  - serverless-s3-sync

functions:
  - ${file(serverless/lambdas.yml)}

resources:
  - ${file(serverless/resources.yml)}

custom:
  conf: ${file(./slsConfig.yml)}
  s3Sync:
    - bucketName: ${self:custom.conf.bucketName}
      localDir: UploadData
